# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# This sample creates a simple InnoDB Cluster. It's similar to sample-cluster.yaml
# but also defines storage requirements for a PersistentVolumeClaim (PVC) set
# as the data directory for MySQL Servers.
# Additional options, like selecting a storage class, can be added.
#
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster-pvc
  namespace: mysql
spec:
  secretName: mypwds
  instances: 3
  version: 8.0.29
  router:
    instances: 1
    version: 8.0.29
  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 3Gi
