---
- hosts: k8s_cluster
  gather_facts: no
  become: yes
  become_user: kube
  
  tasks:
- name: copy kubectl config
  hosts: 172.16.0.11
  become: yes
  gather_facts: no
  tasks:
    - name: get config
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/lukas/.kube/config
        flat: yes
  