---
- hosts: 172.16.0.11
  gather_facts: no
  become: yes

  tasks:
 #  - name: initialize the cluster
 #    become_user: kube
 #    shell: sudo kubeadm init --config=config.yaml --upload-certs
 #    args:
 #     chdir: $HOME
 #     creates: $HOME/.kube/config
 #     executable: /bin/bash

   - name: copies admin.conf to user's kube config
     copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/kube/.kube/config
      remote_src: yes
      owner: kube

   - name: Get the token for joining the worker nodes
     shell: kubeadm token create  --print-join-command --ttl 1h
     become_user: kube
     register: kubernetes_join_command

   - name: k8s join
     debug:
      var: kubernetes_join_command.stdout

   - name: Copy join command to local file.
     become: yes
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: node
  become: yes
  gather_facts: no
  tasks:
   - name: Copy join command from Ansible host to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not