---
- hosts: k8s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: general
      vars:
        upgrading: true
    - role: k8s
    #- role: vitess

- hosts: haproxy
  gather_facts: yes
  become: yes
  roles:
    - role: general
    - role: haproxy
      vars:
        IngressHttpNodePort: 31948
        IngressHttpsNodePort: 31457
    #- role: vitess

#- hosts: master
#  gather_facts: yes
#  become: yes
#  roles:
#    - role: master

- hosts: nfs
  gather_facts: yes
  become: yes
  roles:
    - role: general
    - role: nfs
      vars:
        Path: /mnt/k8s_data
        Network: 172.16.0.0/23

- hosts: tikv
  gather_facts: yes
  become: yes
  roles:
    - role: general
