---

- name: create kube user account
  user:
   name: kube
   append: yes
   state: present
   createhome: yes
   shell: /bin/bash

- name: allow 'kube' to use sudo without needing a password
  lineinfile:
   dest: /etc/sudoers
   line: 'kube ALL=(ALL) NOPASSWD: ALL'
   validate: 'visudo -cf %s'

- name: set up authorized keys for the kube user
  authorized_key: 
   user: kube 
   key: "{{item}}"
  with_file:
   - /home/lukas/.ssh/id_rsa.pub

#- name: add user to docker group
#  user:
#   name: kube
#   append: yes
#   group: docker

- name: create kube config folder
  file:
   path: /home/kube/.kube/
   state: directory
   owner: kube
   group: kube
   mode: 0700